cache:
  - bundler
sudo: false
branches:
  only:
    - master
    - /^release-.*$/

osx_image: xcode7.2
language: objective-c

before_install: ./ci/before_install.sh
bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3

script:
  - ./ci/script.sh
  # This is a workaround for a Travis-CI bug where the log might get cut-off.
  # See the [Travis-CI issue #4716](https://github.com/travis-ci/travis-ci/issues/4716).
  - sleep 3

after_success: ./ci/after_success.sh

deploy:
  provider: releases
  api_key:
    secure: <todo>
  file:
    SPTPersistentCache.framework.zip
  on:
    repo: spotify/SPTPersistentCache
    tags: true
  script: ./ci/deploy.sh


env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - SCHEME_IOS_LIBRARY="SPTPersistentCache"
    - SCHEME_IOS_FRAMEWORK="SPTPersistentCache-iOS"
    - SCHEME_OSX_FRAMEWORK="SPTPersistentCache-OSX"
    - SCHEME_DEMO="SPTPersistentCacheDemo"
    - BUILD="build"
    - BUILD_TEST="build test"
    - ENABLE_CODE_COVERAGE="-enableCodeCoverage YES"
    - PROJECT_LIBRARY="SPTPersistentCache.xcodeproj"
    - PROJECT_DEMO="SPTPersistentCacheDemo/SPTPersistentCacheDemo.xcodeproj"
    - PROJECT_FRAMEWORK="SPTPersistentCacheFramework/SPTPersistentCacheFramework.xcodeproj"
    - PODSPEC="SPTPersistentCache.podspec"
  matrix:
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=8.1,name='iPhone 6'"   SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=8.2,name='iPhone 4s'"  SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=8.3,name='iPhone 5'"   SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=8.4,name='iPhone 5s'"  SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=9.0,name='iPhone 6'"   SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=9.1,name='iPhone 5'"   SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=9.2,name='iPhone 6s'"  SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=macosx           TEST_DEST="platform='OS X',arch=x86_64"                       SCHEME="$SCHEME_IOS_LIBRARY"            BUILD_ACTIONS="$BUILD_TEST" EXTRA_ARGUMENTS="$ENABLE_CODE_COVERAGE" PROJECT="$PROJECT_LIBRARY"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=8.1,name='iPhone 6'"   SCHEME="$SCHEME_DEMO"                   BUILD_ACTIONS="$BUILD"      EXTRA_ARGUMENTS=""                      PROJECT="$PROJECT_DEMO"
    - TEST_SDK=iphonesimulator  TEST_DEST="platform='iOS Simulator',OS=8.1,name='iPhone 6'"   SCHEME="$SCHEME_IOS_FRAMEWORK"          BUILD_ACTIONS="$BUILD"      EXTRA_ARGUMENTS=""                      PROJECT="$PROJECT_FRAMEWORK"
    - TEST_SDK=macosx           TEST_DEST="platform='OS X',arch=x86_64"                       SCHEME="$SCHEME_OSX_FRAMEWORK"          BUILD_ACTIONS="$BUILD"      EXTRA_ARGUMENTS=""                      PROJECT="$PROJECT_FRAMEWORK"
